graph TD
Start>Start] --> BF
Start --> EMS
Start --> REL(Release Day)
REL --> I
EMS(New EMS Version) --> Y[Create new release branch on GitHub]
Y --> C
BF(Bugfix) --> B{Does it affect<br/>multiple releases?}
B -->|Yes|E[Open PR targeting oldest release branch]
E --> D
B -->|No|C[Open PR targeting release branch]
C -->D[Review and merge PR]
D-->G{Is the affected release<br/>already in production?}
D --> F[git cherry-pick to other affected<br/>release branches]
F --> C
G -->|No|H[Finish]
G -->|Yes|I[Open PR from release branch targeting master]
I -->J[Review and merge to master]
J -->K[Test staging website]
K -->L[Deploy to Production]
classDef start fill:#FFDC00,stroke:#333,stroke-width:4px;
class Start start; 
classDef choose fill:#01FF70,stroke:#333,stroke-width:4px;
class BF,EMS,REL choose;