agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1763402084@sha256:41c1a028cdc676c497b6001457a72718a36f86f745709f97c90836859b29d433"
  cpu: "2"
  memory: "4G"

steps:
  - key: build
    label: ":hammer_and_wrench: Build"
    command: ".buildkite/scripts/build.sh"
    artifact_paths: release.tar.gz
    agents:
      cpu: "2"
      memory: "4G"

  - key: deploy-staging
    label: ":rocket: Stage"
    if: build.tag == null && ( build.branch == "master"  || build.branch =~ /^v\d{1,2}\.\d{1,2}$$/ )
    depends_on: build
    command: ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on: build

  - key: deploy-production
    label: ":shipit: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on: should-deploy
    commands:
      - ".buildkite/scripts/archive.sh"
      - ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "production"
