agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node24:1771594567@sha256:7df2fec0e6b90a6d61e83456694de455a544ccd4f4240731d35bbfd9f47b2ea4"  
  cpu: "2"
  memory: "4G"

steps:
  - key: e2e-test
    label: ":playwright: E2E Test"
    command: "yarn install --frozen-lockfile --ignore-engines && yarn test -x"
    env:
      CI: "true"
    artifact_paths: 
      - "test-results/**/*.png"
    agents:
      image: "docker.elastic.co/ci-agent-images/ems/playwright:1774869959-x86_64@sha256:39adeaea22f1e72999068499756f323196c0ab173e4f591597c0996bc661b61d"
      cpu: "2"
      memory: "4G"

  - key: build
    label: ":hammer_and_wrench: Build"
    command: ".buildkite/scripts/build.sh"
    artifact_paths: release.tar.gz
    agents:
      cpu: "2"
      memory: "4G"

  # Wait for e2e test to finish
  - wait: ~

  - key: deploy-staging
    label: ":rocket: Stage"
    if: build.tag == null && ( build.branch == "master"  || build.branch =~ /^v\d{1,2}\.\d{1,2}$$/ )
    depends_on: build
    command: ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on: build

  - key: deploy-production
    label: ":shipit: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on: should-deploy
    commands:
      - ".buildkite/scripts/archive.sh"
      - ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "production"
