agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent:latest"

steps:
  - key: build
    label: ":hammer_and_wrench: Build"
    command: ".buildkite/scripts/build.sh"
    artifact_paths: release.tar.gz
    agents:
      cpu: "2"
      memory: "4G"

  - key: deploy-staging
    label: ":rocket: Stage"
    if: |
      // Deploy to stage for whitelisted branches (also master)
      // and untagged commits
      build.tag == null && 
      build.branch =~ /master|v7\.17|v8\.7|v8\.8/
    depends_on: build
    command: ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy"
    if: |
      // Deploy to production for whitelisted branches
      // and tagged commits
      build.tag != null && 
      build.branch =~ /v7\.17|v8\.7|v8\.8/
    depends_on: build

  - key: deploy-production
    label: ":shipit: Deploy"
    if: |
      // Deploy to production for whitelisted branches
      // and tagged commits
      build.tag != null && 
      build.branch =~ /v7\.17|v8\.7|v8\.8/
    depends_on: should-deploy
    commands:
      - ".buildkite/scripts/archive.sh"
      - ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "production"
