agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1764180808@sha256:5df5cf1a4429922d031d4cbfd635540d3ba3eab0f30f911079e8230880cd8c1c"
  cpu: "2"
  memory: "4G"

steps:
  - key: e2e-test
    label: ":playwright: E2E Test"
    command: /bin/sh -c 'npm install -g yarn && yarn install --frozen-lockfile && yarn test'
    env:
      PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH: "/usr/bin/chromium"
      CI: "true"
    agents:
      image: "docker.elastic.co/ci-agent-images/ems/playwright:0.4.1@sha256:19670b4458abc9aa62ccfc3ee2edb1de7187ddd9e83def42f0db276c4ec5ee03"
      cpu: "2"
      memory: "4G"

  - key: build
    label: ":hammer_and_wrench: Build"
    command: ".buildkite/scripts/build.sh"
    artifact_paths: release.tar.gz
    agents:
      cpu: "2"
      memory: "4G"

  # Wait for e2e test to finish
  - wait: ~

  - key: deploy-staging
    label: ":rocket: Stage"
    if: build.tag == null && ( build.branch == "master"  || build.branch =~ /^v\d{1,2}\.\d{1,2}$$/ )
    depends_on: build
    command: ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on: build

  - key: deploy-production
    label: ":shipit: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on: should-deploy
    commands:
      - ".buildkite/scripts/archive.sh"
      - ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "production"
