agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent:latest"
  cpu: "2"
  memory: "4G"

steps:
  - key: build
    label: ":hammer_and_wrench: Build"
    command: ".buildkite/scripts/build.sh"
    artifact_paths: release.tar.gz


  - key: deploy-staging
    label: ":rocket: Deploy to the staging environment"
    #TODO uncomment this to run only on commits to branches in the Elastic repo
    #branches: "master"
    depends_on: build
    command: ".buildkite/scripts/deploy.sh"
    env:
      EMS_ENVIRONMENT: "staging"

