agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node18:0.1"
  cpu: "2"
  memory: "4G"

steps:
  - label: ":hammer_and_wrench: Build"
    commands: 
      - "yarn install"
      - "yarn build"
