agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node24:1783438567@sha256:24f8a6deec508b11e4e0748df2af4439f888d9d616eabd3beb0891b9184c8edf"
  cpu: "2"
  memory: "4G"

steps:
  - key: e2e-test
    label: ":playwright: E2E Test"
    command: "yarn install --frozen-lockfile --ignore-engines && yarn build-unsafe && yarn test -x"
    env:
      CI: "true"
    artifact_paths: 
      - "test-results/**/*.png"
      - "test-results/**/*.zip"
    agents:
      image: "docker.elastic.co/ci-agent-images/ems/playwright:1783443162-x86_64@sha256:57e6496f7bd2b56c0ffae0eb21a9f46d34875081caf8d2566ba5240e1133f088"
      cpu: "2"
      memory: "4G"

  - key: build
    label: ":hammer_and_wrench: Build"
    command: ".buildkite/scripts/build.sh"
    artifact_paths: release.tar.gz
    agents:
      cpu: "2"
      memory: "4G"

  # Wait for e2e test to finish
  - wait: ~

  - key: deploy-staging
    label: ":rocket: Stage"
    if: build.tag == null && ( build.branch == "master"  || build.branch =~ /^v\d{1,2}\.\d{1,2}$$/ )
    depends_on:
      - build
      - e2e-test
    command: ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "staging"

  - key: should-deploy
    block: ":one-does-not-simply: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on:
      - build
      - e2e-test

  - key: deploy-production
    label: ":shipit: Deploy"
    if: build.tag =~ /(master|v\d{1,2}\.\d{1,2})-\d{4}-\d{2}-\d{2}/
    depends_on: should-deploy
    commands:
      - ".buildkite/scripts/archive.sh"
      - ".buildkite/scripts/upload.sh"
    env:
      EMS_ENVIRONMENT: "production"
