name: Force backport label for sync PRs

on:
  pull_request_target:
    branches:
      - v9.0
      - v8.17
    types:
      - opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1
        with:
          labels: |
            backport
